### PR TITLE
Fix NetInfo isConnected event listeners

### LINKED ISSUE #50: NetInfo.isConnected eventlistener not properly removed on unmount
I've noticed the event listener on NetInfo.isConnected isn't getting removed properly. It seems this was introduced in **Added ability to check connectivity regularly (#32)**.

See:
```javascript
    componentDidMount() {
      NetInfo.isConnected.addEventListener(
        'connectionChange',
        withExtraHeadRequest ? this.checkInternet : this.handleNetInfoChange,
      );
    }
```

and

```javascript
    componentWillUnmount() {
      NetInfo.isConnected.removeEventListener(
        'connectionChange',
        withExtraHeadRequest
          ? this.handleNetInfoChange
          : this.handleConnectivityChange,
      );
    }
```

I'm assuming, based on the change, that the addEventListener should be using this.handleNetInfoChange and this.handleConnectivityChange, though I'm not familiar enough with the project to say that with full confidence.

### PR DESCRIPTION
**Pull request by markvl91**
In line with the changes made in #32.
Fixes #50

### CODE REVIEW

File: src/withNetworkConnectivity.js [hunk 1]
```diff
@@ -59,7 +59,9 @@ const withNetworkConnectivity = (
     componentDidMount() {
       NetInfo.isConnected.addEventListener(
         'connectionChange',
-        withExtraHeadRequest ? this.checkInternet : this.handleNetInfoChange,
+        withExtraHeadRequest
+          ? this.handleNetInfoChange
+          : this.handleConnectivityChange
```
Comment (rauliyohmc) [inline src/withNetworkConnectivity.js]: Prettier is complaining about missing a trailing comma. Sorry, just to keep a consistent code style. Once that's fixed, I'll merge it

**Comment by markvl91** [comment]
I've updated the pull request to add the trailing comma.
